# Generated by Django 2.0.3 on 2018-07-09 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_taskstatus_taskstepstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstatus',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskstepstatus',
            name='task',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
        migrations.DeleteModel(
            name='TaskStepStatus',
        ),
    ]
