# Generated by Django 2.0.3 on 2018-08-03 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180803_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstatus',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskstepstatus',
            name='task_status',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
        migrations.DeleteModel(
            name='TaskStepStatus',
        ),
    ]
