# Generated by Django 2.0.3 on 2018-08-04 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180803_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='task',
        ),
        migrations.RemoveField(
            model_name='stepentry',
            name='step',
        ),
        migrations.RemoveField(
            model_name='stepentry',
            name='task_entry',
        ),
        migrations.RemoveField(
            model_name='taskentry',
            name='task',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
        migrations.DeleteModel(
            name='StepEntry',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskEntry',
        ),
    ]
