# Generated by Django 2.0.3 on 2018-08-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180804_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='task',
        ),
        migrations.RemoveField(
            model_name='stepentry',
            name='step',
        ),
        migrations.RemoveField(
            model_name='stepentry',
            name='task_entry',
        ),
        migrations.RemoveField(
            model_name='taskentry',
            name='task',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
        migrations.DeleteModel(
            name='StepEntry',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskEntry',
        ),
    ]
