# Generated by Django 2.0.3 on 2018-08-07 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180805_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepentry',
            name='due_datetime',
        ),
    ]
